### ISSUE TITLE
Navigation Bar clear button disable

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/chatty-kitchen-towels#18]
## User Experience
As a developer, I need to disable to clear button on empty message box and enable on adding messages.

## Tech Notes
- setting clearButton disable value to true
- enable the clear button when the messages are added.

## Acceptance Criteria 
As a User, when I come to site and click clear button it should remove messages and  disable the button.

**Comment by Shijax** [comment]
Since you are disabling it in the first place, the way to enable it is to set its disabled property as false . To change its disabled property in Javascript, you use this: var btn = document.getElementById("Button"); btn.disabled = false; And obviously to disable it again, you'd use true instead.
