### ISSUE TITLE
Custom Themes Button & Functionality

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/chatty-kitchen-towels#25]
## User Story
When I view the page, there should be a way to choose from several themes.

## Acceptance Criteria
* Have a custom theme button that when pressed will present the user with additional theme options for the page.
* Have at least three custom themes pre-populated for the user to choose from.
* Have a selection of three background colors on the modal.
* Have a selection of three text colors on the modal.

## Tech Notes
• Add a button/link to the UI labeled "Change Theme".
• Remove the existing elements for changing the theme.
• When user click on Change Theme element, show a Bootstrap modal dialog box.
* Inside the modal, show two color picker fields - one for background color and one for font color.
* Add a Save and Cancel button to modal.
* When user clicks Save apply the chosen colors.

**Comment by Shijax** [comment]
Ideas:

## CSS
```
/* -- [ light blue theme (default) ] ---------- */

#header, #header.lightblue {
    background: #ddf;
    height: 80px;
    margin-bottom: 20px;
    width: 300px;
}
#menu, #menu.lightblue {
    background: #ddf;
}

/* -- [ light red theme ] ---------- */

#header.lightred {
    background: #fdd;
    height: 95px;
    margin-bottom: 10px;
    width: 400px;
}
#menu.lightred {
    background: #fdd;
}

/* -- [ light green theme ] ---------- */

#header.lightgreen {
    background: #dfd;
    height: 72px;
    margin-bottom: 15px;
    width: 290px;
}
#menu.lightgreen {
    background: #dfd;
}
```
This way, to change each theme, you just have to change the class of the container object. Say the container object is the document body, then the body's class be changed to the desired theme.

## HTML
```
<div id="swatch">
    <ul>
        <li><a class="theme_option" data-theme="red" href="#">theme1</a></li>
        <li><a class="theme_option" data-theme="green" href="#">theme2</a></li>
        <li><a class="theme_option" data-theme="blue" href="#">theme3</a></li>
    </ul>
</div>
```

## JavaScript (jQuery)
```
jQuery('a.theme_option').click(function(e){
    e.preventDefault();
    var theme_class = jQuery(this).attr('data-theme');
    jQuery(body).attr('class', theme_class);
}
```

**Comment by Shijax** [comment]
Done
