### ISSUE TITLE
Custom Themes Breakdown: #4 - #6

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/chatty-kitchen-towels#26]
## User Story
When I click on the custom theme button I should be able to choose my own theme colors..

## Acceptance Criteria
* Have a selection of three background colors on the modal.
* Have a selection of three text colors on the modal.

## Tech Notes
* Inside the modal, show two color picker fields - one for background color and one for font color.
* Add a Save and Cancel button to modal.
* When user clicks Save apply the chosen colors.

**Comment by zoeames** [comment]
combine this ticket with #25
