### ISSUE TITLE
Message Limit

### ISSUE THREAD

**Issue by JonathanPMohan** [nss-evening-cohort-8/chatty-kitchen-towels#29]
## User Experience
• We want the typed message to be added to the Dom, but only want 20 messages to print at a time.  

## Tech Notes
- Add logic to limit the messages.
- Use the push Method to remove the last message.

## Acceptance Criteria
• Once we have the messages capped at 20 messages visible, then you can move on.

**Comment by zoeames** [comment]
how do you plan to do this?

**Comment by Shijax** [comment]
I have absolutely no clue yet.
